service: taleascrudtask

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-central-1

useDotenv: true

functions:
  index:
    handler: index.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
